import type { Metadata } from "next";
import "./globals.css";
import { ToastProvider } from "@/components/ui/toast";
import { Toaster } from "@/components/ui/toaster"
import { Footer } from "@/components/footer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`subpixel-antialiased font-poppins`}>
        <ToastProvider>
          <div className="relative flex min-h-screen h-full flex-col">
            {children}
            <Footer />
          </div>
        </ToastProvider>
        <Toaster />
      </body>
    </html>
  );
}
