'use client'
import Image from 'next/image';
import Earth from '@/public/static/landing/earth.png'
import indianStreetMan from '@/public/static/landing/indian street.png'
import steveJobs from '@/public/static/landing/steve jobs placeholder 2.png'
import { HeroSection } from '@/components/home/hero-section'
import { FeatureCard } from '@/components/home/feature-card'
import steveplace from '@/public/static/landing/steve jobs placeholder.png'
import Link from 'next/link';
import { useState } from 'react';



export default function HomePage() {
  const [activeCard, setActiveCard] = useState<'founder' | 'investor' | null>(null);
  const isNull = activeCard === null;
  const items =
    activeCard === 'founder' ?

      {
        video: steveplace.src,
        title: "Democratizing Startup Pitching ",
        description: "We're building a new startup economy, where founders can pitch their ideas to 150 investors, in the language they speak."
      }
      :
      activeCard === 'investor' ?
        {
          video: steveplace.src,
          title: "Building a New Startup Economy",
          description: "Discover and invest in promising startups globally, with data-driven insights and localized pitches from diverse founders."
        } :
        {
          video: steveplace.src,
          title: "Sarvodaya",
          description: "Simplifying Startup Scouting and Investment Pitching"
        }
  return (
    <div className=" min-h-screen bg-black w-full  relative  text-white">
      <div className='absolute z-0 w-full left-0   bottom-0 '>
        <Image src={Earth.src} className='z-0 w-full ' alt='earth' width={1000} height={1000} />
      </div>
      <div className='absolute z-0 w-full left-0  flex items-center flex-col   bottom-0 '>
        <span className='text-white text-lg'>Scout Beta Version 0.0.1. </span>
        <span className='text-white text-lg'>©  DaftarOS Technologies 2025 </span>
      </div>

      {/* <NavBar /> */}
      <HeroSection />

      <div className="flex gap-12 z-10 px-10 pl-20 py-10 ">
        <div className="flex gap-5 mr-16 w-1/2">
          <FeatureCard
            image={indianStreetMan.src}
            imageAlt="man working on a laptop generated by Ai"
            title="Democratizing Startup Pitching"
            description="Pitch your startup idea to 150 investors, in the language you speak."
            buttonText="Daftar for Founders"
            isActive={activeCard === 'founder'}
            onClick={() => {
              if (activeCard === 'founder') {
                setActiveCard(null)
              }
              else {
                setActiveCard('founder')
              }
            }
            }
          />

          <FeatureCard
            image={steveJobs.src}
            imageAlt="man working on a laptop generated by Ai"
            title="Scout the next unicorn"
            description="Scout, understand, and build startups with founders across the world."
            buttonText="Daftar for Investors"
            isActive={activeCard === 'investor'}
            onClick={() => {
              if (activeCard === 'investor') {
                setActiveCard(null)
              }
              else {
                setActiveCard('investor')
              }
            }
            }
          />
        </div>

        {/* Center Column */}
        <div className="flex flex-col gap-10  justify-between items-center z-10 w-2/3">
          <div className="py-5 flex flex-col h-[400px]  justify-center gap-5 ">

            <Image
              src={items.video}
              alt="featured content"
              height={450}
              width={550}
            />
            <div className="">
              <h1 className='text-white text-2xl font-bold'>{items.title}</h1>
              <p className='text-gray-400 text-lg max-w-[550px] mt-1'>{items.description}</p>
            </div>
          </div>
          <div className="">
            {!isNull && (
              <div className="flex  justify-center z-10 gap-10">
                <Link className='bg-white text-black px-4 py-2 rounded-lg hover:bg-blue-500 hover:text-white transition-all duration-300' href={`${activeCard}/pricing`}>
                  <button>Pricing</button>
                </Link>
                <Link className='bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-gray-200 hover:text-black transition-all duration-300' href={`/login/${activeCard}`}>
                  <button>Try Daftor for free</button>
                </Link>
              </div>
            )}</div>
        </div>
      </div>
    </div>
  );
}
